<html>
<div class="container" style="margin-top">
<div class="panel panel-primary">
 <div class="panel-heading">
   <h1><center> index </h1></center>
  </div>
    <table class="table table-bordered" >

        <th class="panel-heading"> Id </th>
        <th> First Name </th>
        <th> Last Name </th>
        <th colspan="3"><center> Actions </th></center>

    <?php
        foreach ($this->users as $key => $value) {
          echo "<tr>".
              "<td>". $value['id']."</td>".
              "<td>". $value['fname']."</td>".
              "<td>". $value['lname'] ."</td>".
              "<td><a href='details/uid/".$value['id']."' class='btn btn-success'>Details</a></td>".
              "<td><a href='delete/uid/".$value['id']."'class='btn btn-danger'>Delete</a></td>".
              "<td><a href='edit/uid/".$value['id']."'class='btn btn-primary'>Edit</a></td>".
              "</tr>";
        }
     ?>
   </div>
   </table>
   <div class="panel-body table-borderd">
     <h1> Add Extra Tracks </h1>

       <?php echo $this->track_form ;?>
   </div>
 </div>
 </div>
</html>
