<head>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.
min.css" integrity="sha384-
1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-
theme.min.css" integrity="sha384-
fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
crossorigin="anonymous"></script>
</head>
<?php

  echo <<<EOL
  <nav class=" navbar-inverse" style='margin-bottom: 0'>
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href='index.php'>Zend | Open Source </a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">

  <li><a href="/User/list"> Home </a></li>
  <li><a href="/User/add"> New User</a></li>
  <li><a href=""> About </a></li>
    </ul>

  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>
EOL;
  ?>
<!-- /**************** create and all users buttons ********************/ -->
<?php
$auth = Zend_Auth::getInstance();
$identity = $auth->getIdentity();
// $myarray = (array)$identity;
// $value = key($myarray);
// var_dump($value);
// die();
$fbObjName = new Zend_Session_Namespace('facebook');
if (!empty($identity)) {
    echo "welcome"."  ".$identity->fname.' '.$identity->lname ."<br>";
    echo "<a href='/user/logout' class='btn btn-danger'>logout</a>";
  }
  else if ($fbObjName->fname) {
      echo "welcome"."  ".$fbObjName->fname ."<br>";
      echo "<a href='/user/logout' class='btn btn-danger'>logout</a>";
    }
  else {
    echo "<a href='/user/login' class='btn btn-success'>login</a>";
  }
  ?>
  <hr>
  <h3><a href="/user/add" class="btn btn-primary">Create New User</a>
  <a href="/user/list" class="btn btn-danger">All Users</a></h3>
  <hr>
<?php echo $this->layout()->content; ?>

<div style ="background:black;">
<hr>
<center >
   <h1 bgcolor="black">   open source   </h1>
</center>
<hr>

</div>
